/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba_sqlserver;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Iliana, Erick y Juan
 */
public class Principal extends javax.swing.JFrame {

    boolean comprobar, comprobar2;

    public Principal() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_inicio = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        tp_inicio = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_table = new javax.swing.JList<>();
        cb_crud = new javax.swing.JComboBox<>();
        jb_actualizar = new javax.swing.JButton();
        jb_seleccionar = new javax.swing.JButton();
        jb_cargar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jt_mostrar = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_tablas2 = new javax.swing.JList<>();
        jb_izquierda = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_tablas = new javax.swing.JList<>();
        jb_derecha = new javax.swing.JButton();
        jb_guardar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jb_replicar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_instancia_o = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_bd_o = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_puerto_o = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_usuario_o = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pf_clave_o = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tf_instancia_d = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_db_d = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_puerto_d = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_usuario_d = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pf_clave_d = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jb_iniciar = new javax.swing.JButton();
        jb_probar_destino = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jb_probar_origen = new javax.swing.JButton();

        tp_inicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tp_inicioStateChanged(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Acciones");

        jl_table.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_table);

        cb_crud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar", "Modificar", "Eliminar" }));

        jb_actualizar.setText("Actualizar");
        jb_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_actualizarMouseClicked(evt);
            }
        });

        jb_seleccionar.setText("Seleccionar");
        jb_seleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_seleccionarMouseClicked(evt);
            }
        });

        jb_cargar.setText("Cargar");
        jb_cargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cargarMouseClicked(evt);
            }
        });

        jt_mostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LLave Primaria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jt_mostrar);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(cb_crud, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(99, 99, 99))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jb_actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_seleccionar)))
                .addGap(62, 62, 62)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_cargar))
                .addGap(0, 54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(225, 225, 225))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel14)
                .addGap(27, 27, 27)
                .addComponent(cb_crud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_actualizar)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jb_seleccionar)
                        .addComponent(jb_cargar)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tp_inicio.addTab("Acciones", jPanel5);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jl_tablas2.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_tablas2);

        jb_izquierda.setText("⬅");
        jb_izquierda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_izquierdaMouseClicked(evt);
            }
        });

        jl_tablas.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_tablas);

        jb_derecha.setText("➡");
        jb_derecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_derechaMouseClicked(evt);
            }
        });

        jb_guardar.setText("Guardar");
        jb_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarMouseClicked(evt);
            }
        });

        jb_cancelar.setText("Cancelar");
        jb_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cancelarMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel15.setText("No Replicados");

        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel16.setText("Replicados");

        jb_replicar.setText("Replicar");
        jb_replicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_replicarMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("Replicar");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel15)
                        .addGap(223, 223, 223)
                        .addComponent(jLabel16))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jb_guardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jb_cancelar))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_replicar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jb_derecha)
                            .addComponent(jb_izquierda))
                        .addGap(33, 268, Short.MAX_VALUE))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_guardar)
                    .addComponent(jb_cancelar))
                .addGap(46, 46, 46))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel17)
                        .addGap(102, 102, 102)
                        .addComponent(jb_derecha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jb_izquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_replicar)))
                .addGap(35, 43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tp_inicio.addTab("Replicar", jPanel9);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tp_inicio)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(tp_inicio)
                .addContainerGap())
        );

        javax.swing.GroupLayout jd_inicioLayout = new javax.swing.GroupLayout(jd_inicio.getContentPane());
        jd_inicio.getContentPane().setLayout(jd_inicioLayout);
        jd_inicioLayout.setHorizontalGroup(
            jd_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_inicioLayout.setVerticalGroup(
            jd_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nombre Instancia:");

        tf_instancia_o.setText("localhost");

        jLabel2.setText("Nombre Base Datos:");

        tf_bd_o.setText("computer");

        jLabel3.setText("Puerto:");

        tf_puerto_o.setText("1433");

        jLabel4.setText("Nombre de usuario:");

        tf_usuario_o.setText("sa");

        jLabel5.setText("Clave:");

        pf_clave_o.setText("123");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tf_instancia_o, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_bd_o, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_puerto_o, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(tf_usuario_o)
                            .addComponent(pf_clave_o))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_instancia_o, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_bd_o, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_puerto_o, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_usuario_o, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pf_clave_o, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Base de Datos Origen");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Nombre Instancia:");

        tf_instancia_d.setText("localhost");

        jLabel8.setText("Nombre Base Datos:");

        tf_db_d.setText("computer");

        jLabel9.setText("Puerto:");

        tf_puerto_d.setText("3306");

        jLabel10.setText("Nombre de usuario:");

        tf_usuario_d.setText("root");

        jLabel11.setText("Clave:");

        pf_clave_d.setText("Iliana98maria");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tf_instancia_d, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_db_d, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_puerto_d, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(tf_usuario_d)
                            .addComponent(pf_clave_d))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_instancia_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_db_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_puerto_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_usuario_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pf_clave_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Base de Datos Destino");

        jb_iniciar.setText("Iniciar");
        jb_iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_iniciarMouseClicked(evt);
            }
        });

        jb_probar_destino.setText("Probar");
        jb_probar_destino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_probar_destinoMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Proyecto TBD2");

        jb_probar_origen.setText("Probar");
        jb_probar_origen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_probar_origenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jb_iniciar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jb_probar_origen)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jb_probar_destino, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(35, 35, 35))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_probar_destino)
                    .addComponent(jb_probar_origen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jb_iniciar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_probar_origenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_probar_origenActionPerformed
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://" + tf_instancia_o.getText() + ":" + tf_puerto_o.getText() + ";databaseName=" + tf_bd_o.getText() + ";integratedSecurity=true;";
            Connection conexion = DriverManager.getConnection(connectionUrl);
            System.out.println("Conectado");
            System.out.println("----------");
            comprobar = true;
            JOptionPane.showMessageDialog(this, "¡Base de datos conectada exitosamente!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "¡Base de datos no encontrada!");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "¡Base de datos no encontrada!");
        }
    }//GEN-LAST:event_jb_probar_origenActionPerformed

    private void jb_iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_iniciarMouseClicked
        if (comprobar && comprobar2) {
            comprobar = false;
            comprobar2 = false;
            jd_inicio.pack();
            jd_inicio.setModal(true);
            jd_inicio.setLocationRelativeTo(this);
            jd_inicio.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "¡Debe probar las bases de datos antes de iniciar!");
        }
    }//GEN-LAST:event_jb_iniciarMouseClicked

    private void jb_probar_destinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_probar_destinoMouseClicked
        String url = "jdbc:mysql://" + tf_instancia_d.getText() + ":" + tf_puerto_d.getText() + "/" + tf_db_d.getText() + "";
        String user = tf_usuario_d.getText();
        String pass = pf_clave_d.getText();
        System.out.println("Conectando...");
        try (Connection connection = DriverManager.getConnection(url, user, pass)) {
            JOptionPane.showMessageDialog(this, "Base de datos conectada exitosamente");
            comprobar2 = true;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Base de datos no encontrada");
        }
    }//GEN-LAST:event_jb_probar_destinoMouseClicked

    private void jb_derechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_derechaMouseClicked
        try {
            DefaultListModel m = (DefaultListModel) jl_tablas.getModel();
            DefaultListModel m2 = (DefaultListModel) jl_tablas2.getModel();
            m2.addElement(m.getElementAt(jl_tablas.getSelectedIndex()));
            m.removeElement(m.getElementAt(jl_tablas.getSelectedIndex()));
        } catch (Exception e) {
            //e.printStackTrace();
        }
    }//GEN-LAST:event_jb_derechaMouseClicked

    private void jb_izquierdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_izquierdaMouseClicked
        try {
            DefaultListModel m = (DefaultListModel) jl_tablas.getModel();
            DefaultListModel m2 = (DefaultListModel) jl_tablas2.getModel();
            m.addElement(m2.getElementAt(jl_tablas2.getSelectedIndex()));
            m2.removeElement(m2.getElementAt(jl_tablas2.getSelectedIndex()));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jb_izquierdaMouseClicked

    private void jb_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cancelarMouseClicked
        try {
            ArrayList<String> nombres = new ArrayList();
            Statement st2 = conectSQLServer().createStatement();
            ResultSet rs2 = st2.executeQuery("SELECT NOMBRE FROM BITACORA");
            while (rs2.next()) {
                nombres.add(rs2.getString(1));
            }
            DefaultListModel m = (DefaultListModel) jl_tablas.getModel();
            DefaultListModel m2 = (DefaultListModel) jl_tablas2.getModel();
            Statement st = conectSQLServer().createStatement();
            ResultSet rs = st.executeQuery("SELECT name FROM sysobjects where type='U'");
            while (rs.next()) {
                if (!rs.getString(1).equalsIgnoreCase("Bitacora")) {
                    int entrar = 0;
                    for (int i = 0; i < nombres.size(); i++) {
                        if (nombres.get(i).equalsIgnoreCase(rs.getString(1))) {
                            entrar = 1;
                        }
                    }
                    if (entrar == 0) {
                        m.addElement(rs.getString(1));
                    } else {
                        m2.addElement(rs.getString(1));
                    }
                }
            }
        } catch (Exception e) {
            //e.printStackTrace();
        }
    }//GEN-LAST:event_jb_cancelarMouseClicked

    private void tp_inicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tp_inicioStateChanged
        try {
            int num = tp_inicio.getSelectedIndex();
            if (num == 1) {
                ArrayList<String> nombres = new ArrayList();
                Statement st2 = conectSQLServer().createStatement();
                ResultSet rs2 = st2.executeQuery("SELECT NOMBRE FROM BITACORA");
                while (rs2.next()) {
                    nombres.add(rs2.getString(1));
                }
                DefaultListModel m = (DefaultListModel) jl_tablas.getModel();
                DefaultListModel m2 = (DefaultListModel) jl_tablas2.getModel();
                m.removeAllElements();
                m2.removeAllElements();
                Statement st = conectSQLServer().createStatement();
                ResultSet rs = st.executeQuery("SELECT name FROM sysobjects where type='U'");
                while (rs.next()) {
                    String nombre = rs.getString(1);
                    if (!nombre.equals("Bitacora") && !nombre.equals("Bitacora2") && !nombre.equals("Historial")) {
                        int entrar = 0;
                        for (int i = 0; i < nombres.size(); i++) {
                            if (nombres.get(i).equals(nombre)) {
                                entrar = 1;
                            }
                        }
                        if (entrar == 0) {
                            m.addElement(nombre);
                        } else {
                            m2.addElement(nombre);
                        }
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tp_inicioStateChanged

    private void jb_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarMouseClicked
        try {
            DefaultListModel m = (DefaultListModel) jl_tablas2.getModel();
            Statement st = conectSQLServer().createStatement();
            st.execute("DELETE FROM BITACORA");
            for (int i = 0; i < m.size(); i++) {
                st.execute("INSERT INTO BITACORA VALUES('" + m.getElementAt(i) + "')");
            }
            JOptionPane.showMessageDialog(jd_inicio, "¡Guardado Exitoso!");
        } catch (Exception e) {
            //e.printStackTrace();
        }
    }//GEN-LAST:event_jb_guardarMouseClicked

    private void jb_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_actualizarMouseClicked
        try {
            DefaultListModel m = (DefaultListModel) jl_table.getModel();
            m.removeAllElements();
            Statement st = conectSQLServer().createStatement();
            ResultSet rs = st.executeQuery("SELECT name FROM sysobjects where type='U'");
            while (rs.next()) {
                if (!rs.getString(1).equalsIgnoreCase("Bitacora") && !rs.getString(1).equalsIgnoreCase("Bitacora2") && !rs.getString(1).equalsIgnoreCase("Historial")) {
                    m.addElement(rs.getString(1));
                }
            }
        } catch (Exception e) {
            //e.printStackTrace();
        }
    }//GEN-LAST:event_jb_actualizarMouseClicked

    private void jb_seleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_seleccionarMouseClicked
        try {
            ArrayList<String> atributos = new ArrayList();
            ArrayList<String> tipos = new ArrayList();
            Statement st = conectSQLServer().createStatement();
            DefaultListModel m = (DefaultListModel) jl_table.getModel();
            if (jl_table.getSelectedIndex() >= 0) {
                //meter los atributos a un arraylist
                String tabla = m.getElementAt(jl_table.getSelectedIndex()) + "";
                ResultSet rs = st.executeQuery("SELECT c.name FROM sys.columns c JOIN sys.tables t ON c.object_id = t.object_id WHERE t.name = " + "'" + tabla + "'");
                while (rs.next()) {
                    atributos.add(rs.getString(1));
                }
                ResultSet rs10 = st.executeQuery("Select  data_type from information_schema.columns WHERE TABLE_NAME='" + tabla + "'");
                while (rs10.next()) {
                    tipos.add(rs10.getString(1));
                }
                DefaultComboBoxModel combo = (DefaultComboBoxModel) cb_crud.getModel();
                String tipo = combo.getSelectedItem() + "";
                //verificar los cruds
                if (tipo.equals("Agregar")) {
                    String acum = "INSERT INTO " + tabla + " VALUES(";
                    for (int i = 0; i < atributos.size(); i++) {
                        String atributo = JOptionPane.showInputDialog(jd_inicio, "Ingrese " + atributos.get(i) + ":");
                        if (tipos.get(i).equalsIgnoreCase("varchar")) {
                            acum += "'" + atributo + "'";
                        } else {
                            acum += "" + atributo + "";
                        }
                        if (i == atributos.size() - 1) {
                            acum += ")";
                        } else {
                            acum += ",";
                        }
                    }
                    st.execute(acum);
                    JOptionPane.showMessageDialog(jd_inicio, "¡Agregado Exitoso!");
                } else if (tipo.equals("Modificar")) {
                    String acum = "";
                    for (int i = 0; i < atributos.size(); i++) {
                        acum += (i + 1) + "). " + atributos.get(i) + "\n";
                    }

                    ArrayList<String> llaves = new ArrayList();
                    ResultSet rs2 = st.executeQuery("SELECT [name]\n"
                            + "FROM syscolumns \n"
                            + "WHERE [id] IN (\n"
                            + "    SELECT [id] FROM sysobjects \n"
                            + "    WHERE [name] = '" + tabla + "' )\n"
                            + "    AND colid IN (\n"
                            + "    SELECT SIK.colid \n"
                            + "    FROM sysindexkeys SIK JOIN sysobjects SO ON SIK.[id] = SO.[id]\n"
                            + "    WHERE SIK.indid = 1 AND SO.[name] = '" + tabla + "' )");
                    while (rs2.next()) {
                        llaves.add(rs2.getString(1));
                    }
                    String llave = JOptionPane.showInputDialog(jd_inicio, "Ingrese la llave primaria que desea modificar: ");
                    ResultSet verify1 = st.executeQuery("SELECT * FROM " + tabla + " WHERE " + llaves.get(0) + " = " + llave);
                    if (verify1.next()) {
                        int algo = Integer.parseInt(JOptionPane.showInputDialog(jd_inicio, "Que desea modificar? \n " + acum));
                        String atributo = JOptionPane.showInputDialog(jd_inicio, "Ingrese el valor:");
                        if (tabla.equalsIgnoreCase("product")) {
                            st.execute("UPDATE " + tabla + " SET " + atributos.get(algo - 1) + " = '" + atributo + "' WHERE " + llaves.get(0) + " = '" + llave + "'");
                        } else {
                            st.execute("UPDATE " + tabla + " SET " + atributos.get(algo - 1) + " = '" + atributo + "' WHERE " + llaves.get(0) + " = " + llave);

                        }
                        JOptionPane.showMessageDialog(jd_inicio, "¡Modificado Exitoso!");
                    } else {
                        JOptionPane.showMessageDialog(jd_inicio, "¡El registro no existe!");
                    }

                } else if (tipo.equals("Eliminar")) {
                    String atributo = JOptionPane.showInputDialog(jd_inicio, "Ingrese la llave primaria");

                    ArrayList<String> foraneas = new ArrayList();
                    ResultSet rs3 = st.executeQuery("SELECT SYSCOLUMNS.name as field\n"
                            + "FROM SYSCOLUMNS \n"
                            + "INNER JOIN SYSOBJECTS ON SYSOBJECTS.ID = SYSCOLUMNS.ID \n"
                            + "WHERE SYSOBJECTS.name = '" + tabla + "' \n"
                            + "and SYSCOLUMNS.xtype = '56';");
                    while (rs3.next()) {
                        foraneas.add(rs3.getString(1));
                    }
                    ResultSet verify = st.executeQuery("SELECT * FROM " + tabla + " WHERE " + foraneas.get(0) + " = " + atributo);
                    if (verify.next()) {
                        if (foraneas.size() > 0) {
                            Statement stB = conectSQLServer().createStatement();
                            stB.execute("DELETE FROM " + tabla + " WHERE " + foraneas.get(0) + " = " + atributo + "");
                            JOptionPane.showMessageDialog(jd_inicio, "¡Eliminado Exitoso!");
                        }
                    } else {
                        JOptionPane.showMessageDialog(jd_inicio, "¡El registro no existe!");
                    }

                }
            } else {
                JOptionPane.showMessageDialog(jd_inicio, "¡No ha seleccionado una tabla!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_inicio, "¡Datos incorrectos!");
        }
    }//GEN-LAST:event_jb_seleccionarMouseClicked

    private void jb_cargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cargarMouseClicked
        try {
            DefaultTableModel table = (DefaultTableModel) jt_mostrar.getModel();
            table.setRowCount(0);
            DefaultListModel m = (DefaultListModel) jl_table.getModel();
            if (jl_table.getSelectedIndex() >= 0) {
                String tabla = m.getElementAt(jl_table.getSelectedIndex()) + "";
                Statement st = conectSQLServer().createStatement();
                ArrayList<String> llaves = new ArrayList();
                ResultSet rs2 = st.executeQuery("SELECT [name]\n"
                        + "FROM syscolumns \n"
                        + "WHERE [id] IN (\n"
                        + "    SELECT [id] FROM sysobjects \n"
                        + "    WHERE [name] = '" + tabla + "' )\n"
                        + "    AND colid IN (\n"
                        + "    SELECT SIK.colid \n"
                        + "    FROM sysindexkeys SIK JOIN sysobjects SO ON SIK.[id] = SO.[id]\n"
                        + "    WHERE SIK.indid = 1 AND SO.[name] = '" + tabla + "' )");
                while (rs2.next()) {
                    llaves.add(rs2.getString(1));
                }
                for (int i = 0; i < llaves.size(); i++) {
                    ResultSet rs3 = st.executeQuery("SELECT " + llaves.get(i) + " from " + tabla);
                    String acum = "";
                    while (rs3.next()) {
                        acum += " " + rs3.getString(1) + " \n";
                        Object[] row = {rs3.getString(1)};
                        table.addRow(row);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(jd_inicio, "No ha seleccionado una tabla");
            }
        } catch (Exception e) {
            //e.printStackTrace();
        }
    }//GEN-LAST:event_jb_cargarMouseClicked

    private void jb_replicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_replicarMouseClicked
        try {
            Statement st = conectSQLServer().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM BITACORA");
            ArrayList<String> tablas = new ArrayList();
            while (rs.next()) {
                tablas.add(rs.getString(1));
            }
            ResultSet rs2 = st.executeQuery("SELECT * FROM BITACORA2");
            ArrayList<Bitacora> bitacoras = new ArrayList();
            while (rs2.next()) {
                bitacoras.add(new Bitacora(rs2.getString(1), rs2.getString(2), rs2.getString(3), rs2.getDate(4) + " " + rs2.getTime(4)));
            }
            for (int i = 0; i < bitacoras.size(); i++) {
                boolean entrar = true;
                for (int j = 0; j < tablas.size(); j++) {
                    if (bitacoras.get(i).getNombre().equalsIgnoreCase(tablas.get(j))) {
                        entrar = false;
                    }
                }
                if (!entrar) {
                    String temp = bitacoras.get(i).getDescripcion();
                    String accion = "";
                    int primero = 0, segundo = 0;
                    boolean entrar2 = true;
                    for (int j = 0; j < temp.length(); j++) {
                        if (temp.charAt(j) == '*') {
                            accion += "'";
                        } else {
                            accion += temp.charAt(j);
                        }
                        if (temp.charAt(j) == '(') {
                            primero = j;
                        } else {
                            if (temp.charAt(j) == ',' && entrar2) {
                                segundo = j;
                                entrar2 = false;
                            }
                        }
                    }
                    ResultSet rs3 = st.executeQuery("SELECT [name]\n"
                            + "FROM syscolumns \n"
                            + "WHERE [id] IN (\n"
                            + "    SELECT [id] FROM sysobjects \n"
                            + "    WHERE [name] = '" + bitacoras.get(i).getNombre() + "' )\n"
                            + "    AND colid IN (\n"
                            + "    SELECT SIK.colid \n"
                            + "    FROM sysindexkeys SIK JOIN sysobjects SO ON SIK.[id] = SO.[id]\n"
                            + "    WHERE SIK.indid = 1 AND SO.[name] = '" + bitacoras.get(i).getNombre() + "' )");

                    String campo = "";
                    while (rs3.next()) {
                        campo = rs3.getString(1);
                    }
                    Statement st2 = conectMySQL().createStatement();
                    if (bitacoras.get(i).getAccion().equals("Modifico")) {
                        String llave = accion.substring(primero + 1, segundo);
                        System.out.println("eliminar, " + campo + ", " + llave);
                        st2.execute("DELETE FROM " + bitacoras.get(i).getNombre() + " WHERE " + campo + " = " + llave);
                    }
                    System.out.println("accion: " + accion);
                    st2.execute(accion);
                }
            }
            for (int i = 0; i < bitacoras.size(); i++) {
                st.execute("INSERT INTO HISTORIAL VALUES('" + bitacoras.get(i).getNombre() + "','" + bitacoras.get(i).getAccion() + "','" + bitacoras.get(i).getDescripcion() + "','" + bitacoras.get(i).getFecha() + "')");
            }
            st.execute("DELETE FROM BITACORA2");
            JOptionPane.showMessageDialog(jd_inicio, "Replica Exitosa");
        } catch (Exception e) {
            //e.printStackTrace();
        }
    }//GEN-LAST:event_jb_replicarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    public Connection conectMySQL() {
        String url = "jdbc:mysql://localhost:3306/computer";
        String user = "root";
        String pass = "Iliana98maria";
        System.out.println("Conectando...");
        Connection dbcon = null;
        try {
            dbcon = DriverManager.getConnection(url, user, pass);
            Statement st = dbcon.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        return dbcon;
    }

    public Connection conectSQLServer() {
        Connection conexion = null;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://" + tf_instancia_o.getText() + ":" + tf_puerto_o.getText() + ";databaseName=" + tf_bd_o.getText() + ";integratedSecurity=true;";
            conexion = DriverManager.getConnection(connectionUrl);
        } catch (Exception e) {
        }
        return conexion;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_crud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jb_actualizar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_cargar;
    private javax.swing.JButton jb_derecha;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_iniciar;
    private javax.swing.JButton jb_izquierda;
    private javax.swing.JButton jb_probar_destino;
    private javax.swing.JButton jb_probar_origen;
    private javax.swing.JButton jb_replicar;
    private javax.swing.JButton jb_seleccionar;
    private javax.swing.JDialog jd_inicio;
    private javax.swing.JList<String> jl_tablas;
    private javax.swing.JList<String> jl_tablas2;
    private javax.swing.JList<String> jl_table;
    private javax.swing.JTable jt_mostrar;
    private javax.swing.JPasswordField pf_clave_d;
    private javax.swing.JPasswordField pf_clave_o;
    private javax.swing.JTextField tf_bd_o;
    private javax.swing.JTextField tf_db_d;
    private javax.swing.JTextField tf_instancia_d;
    private javax.swing.JTextField tf_instancia_o;
    private javax.swing.JTextField tf_puerto_d;
    private javax.swing.JTextField tf_puerto_o;
    private javax.swing.JTextField tf_usuario_d;
    private javax.swing.JTextField tf_usuario_o;
    private javax.swing.JTabbedPane tp_inicio;
    // End of variables declaration//GEN-END:variables
ArrayList<String> llaveprimaria = new ArrayList();
}
